### ISSUE TITLE
Need logo for desktop and single letter icon for mobile

### ISSUE THREAD

**Issue by nihalanisumit** [pesto-students/batch-9-Lumen#159]

**Comment by piyushagwl007** [comment]
I have uploaded logos to the cloudniary to get optimized image and transform on the fly.
Full width logo:
https://res.cloudinary.com/dw1omslee/image/upload/v1567267732/Lumen/logo-full_hozy1u.png

Mobile logo:
https://res.cloudinary.com/dw1omslee/image/upload/v1567267475/Lumen/Lumen-logo-mobile_lgjgq7.png

Transformation example:
1. mobile logo width 100px : https://res.cloudinary.com/dw1omslee/image/upload/c_scale,w_100/v1567267475/Lumen/Lumen-logo-mobile_lgjgq7.png
2. desktop logo width 100px: https://res.cloudinary.com/dw1omslee/image/upload/c_scale,w_100/v1567267732/Lumen/logo-full_hozy1u.png
