### ISSUE TITLE
PR template not working

### ISSUE THREAD

**Issue by piyushagwl007** [pesto-students/batch-9-Lumen#42]
Check the [P.R.](https://github.com/pesto-students/batch-9-Lumen/pull/41)

![image](https://user-images.githubusercontent.com/26798929/63059295-a62d2500-bf0c-11e9-9216-fbbeb8c61e89.png)

I expected the P.R. to be present when I created this P.R. 
My branch has contributing.md in it still it did not create the expected P.R. format.

**Comment by karansapolia** [comment]
As discussed on Slack, the issue was because `.github` was committed to the `dev` branch but `master` was set as the default branch. The template works only if it is committed to the default branch of the repo.

**Comment by karansapolia** [comment]
Functioning now that `dev` is set to default
![Screenshot from 2019-08-15 03-52-08](https://user-images.githubusercontent.com/10175625/63060528-2e60f980-bf10-11e9-8aef-c102fbc2c063.png)
