### ISSUE TITLE
Discuss the likes and comments structure for the application 

### ISSUE THREAD

**Issue by piyushagwl007** [pesto-students/batch-9-Lumen#79]
## Current DB schema:
```
BLOGS: 
{
userId: {type: ObjectId, ref: userModel},
title: {type:String},
content: [
     {
     _id,
     type,
     content
   }
   ],
likes:[userArray],
private: boolean,
}
```
## Proposed DB schema.

Read about storing comments in mongoDB from [here](https://docs.mongodb.com/ecosystem/use-cases/storing-comments/) .
Thinking of going with the approach with [One Document Per Comment with Parent Id to support replies](https://docs.mongodb.com/ecosystem/use-cases/storing-comments/#one-document-per-comment).   Also, I am thinking of not going with the slug part mentioned in the proposed schema because we don't have that kind of requirement. :smile: 
```
Categories:

{
 _id: ObjectID,
name: {type:String},
}


Blogs:
{
userId: {type: ObjectId, ref: userModel},
title: {type:String},
//changing the content schema to support our markdown string as we have figured out embedding and video using markdown string only.
content: {type: String()},
private: boolean,
//the published will help us in solving the draft feature
published: boolean,
category:{type:ObjectId, ref: 'Categories'}
}

Comments: 

{
    _id: ObjectId(...),
    blogId: ObjectId(...),
    parentId: ObjectId(...),
    posted: ISODateTime(...),
    author: {
              id: ObjectId(...),
             
             },
    text: 'This is so bogus ... '
}

User Votes: 
{
userId: ObjectId,
blogId: ObjectId,
vote: +1 or -1
}
```
@nimish-gupta @rishabh1403 If you guys can give some insighths here it would be very helpful to us

**Comment by karansapolia** [comment]
@piyushagwl007 
> Comments: 
> 
> {
>     _id: ObjectId(...),
>     discussion_id: ObjectId(...),
>     parent_id: ObjectId(...),
>     posted: ISODateTime(...),
>     author: {
>               id: ObjectId(...),
>              
>              },
>     text: 'This is so bogus ... '
> }

How will the discussion_id key be used here?

The mongo link mentions that:
> the discussion_id field that references the discussion parent,

Does that indicate a nested comments structure? Comment -> reply -> reply ?

**Comment by piyushagwl007** [comment]
@karansapolia Sorry I copy-pasted the structure mentioned in the docs of MongoDB.    The discussion_id represents the blogId. Sorry for the confusion. I have updated in the comments as well.

**Comment by karansapolia** [comment]
> User Votes: 
> {
> userId: ObjectId,
> blogId: ObjectId,
> vote: +1 or -1
> }

I don't exactly understand this model. Isn't this creating a document for each upvote and downvote for every blog? If so, do we need this? How would this be beneficial over having a `votes` key in the Blogs schema which would aggregate the number of votes received by a blog? Do we need to track all the blogs that a user likes or dislikes?

**Update**: Ok, understood from [here](https://stackoverflow.com/questions/12147686/storing-upvotes-downvotes-in-mongodb/12148306#12148306)

**Comment by karansapolia** [comment]
Seems a good approach @piyushagwl007

**Comment by piyushagwl007** [comment]
After the discussion, we are going with the proposed DB design
